- src/main/kotlin/graph/model/Edge.kt
- src/main/kotlin/graph/model/Graph.kt
- src/main/kotlin/graph/model/Vertex.kt
-add first version of edge class
> Edge class

- src/main/kotlin/algorithms/Algo.kt
> feat: add empty folders for secondary algorithms

- src/main/kotlin/algorithms/BridgeFinder.kt
This is raw implementation of bridge finder algorithm. In the future it should be adapt to specifc task and support multiple edges
> Bridge finder

- src/main/kotlin/algorithms/FordBellman.kt
- src/main/kotlin/graph/model/Edge.kt
This is raw version of Ford-Bellman algorithm for shortest path find.
> Ford bellman algorithm

- build.gradle.kts
- gradle.properties
Add necessary dependencies for work with databases by JetBrains exposed framework. Also add necessary directories for future work
> Database sql

- src/main/kotlin/viewmodel/layouts/CircularLayout.kt
- src/main/kotlin/viewmodel/layouts/RepresentationStrategy.kt
Implement raw version of basic circular layout
> Circular graph layout

- src/main/kotlin/viewmodel/Canvas.kt
- src/main/kotlin/viewmodel/CanvasViewModel.kt
implement viewmodel for main screen
> feat: add canvas view model

- src/main/kotlin/viewmodel/graph/GraphViewModel.kt
> Fix edges view

- src/main/kotlin/algorithms/Kosaraju.kt
The algorithm has been rewritten and now works properly. 
Now the algorithm performs the steps in the correct order. 
Now the algorithm returns the components of strong connectivity as a list of vertex ids
> feat(algo): kosaraju algo returns component's

- src/main/kotlin/view/graph/VertexView.kt
- src/main/kotlin/viewmodel/CanvasViewModel.kt
- src/main/kotlin/viewmodel/graph/GraphViewModel.kt
- src/main/kotlin/viewmodel/graph/VertexViewModel.kt
visible labels with vertices data
> feat: add lables for vertices

- build.gradle.kts
- src/main/kotlin/Main.kt
- src/main/kotlin/algorithms/BridgeFinder.kt
- src/main/kotlin/graph/model/Graph.kt
- src/test/kotlin/graphs/algorithms/BridgeFinderTest.kt
- src/test/kotlin/graphs/algorithms/DjikstraTest.kt
- src/test/kotlin/graphs/algorithms/KosajaruTest.kt
Fixed addVertex function. Implement working brdigefinder algorithm with multiple edges support. Add 1 test for it
> BridgeFinder Work

- src/test/kotlin/graphs/algorithms/BridgeFinderTest.kt
- src/test/kotlin/graphs/algorithms/FordBellmanTest.kt
> fix: typos

- src/main/kotlin/algorithms/FordBellman.kt
- src/test/kotlin/graphs/algorithms/FordBellmanTest.kt
Fixed bugs in Ford Bellman algorithm. Add test for it.
> Ford bellman algorithm test

- src/test/kotlin/graphs/algorithms/LouvainTest.kt
feat(tests): Louvain test added
> feat(tests): Louvain test added

- src/main/kotlin/controller/GraphPainter.kt
feat(ui): graph painting by community
> feat(ui): graph painting by community

- build.gradle.kts
- src/main/kotlin/Main.kt
- src/main/kotlin/model/databases/neo4j/Neo4jDBHandler.kt
- src/main/kotlin/model/databases/neo4j/Repository.kt
- src/main/kotlin/model/graph/Graph.kt
- src/main/kotlin/view/AlgorithmSubMenu.kt
- src/main/kotlin/view/CanvasView.kt
- src/main/kotlin/view/NavigationDrawer.kt
- Add left dynamic menu
- Add submenu for algorithms
- Add buttons and scaffold
> GUI raw version

- .github/formatter.yml
- build.gradle.kts
- scripts/pre-commit
- Add formatter
- Add precommit-hooks
> CI features

- src/main/kotlin/view/AlgorithmSubMenu.kt
Buttons for teammates and their algorithms
> Add buttons for algorithms

- src/main/kotlin/view/CanvasView.kt
- src/main/kotlin/view/NavigationDrawer.kt
- src/main/kotlin/viewmodel/CanvasViewModel.kt
> Graph save

- src/main/kotlin/view/CanvasView.kt
added extra bonus lootbet betboom ligastavok
> feat(ui): graph save neo4j implementation

- src/main/kotlin/view/CustomRadioView.kt
- src/main/kotlin/view/LoadGraphMenu.kt
Small cosmetic fixes and different and ability to load graph from different types of storages
> feat(ui): add different types of storages support

- src/main/kotlin/model/databases/sqlite/SQLiteDBHandler.kt
- src/main/kotlin/model/databases/sqlite/dao/edge/Edges.kt
- src/main/kotlin/view/LoadGraphMenu.kt
- src/main/kotlin/viewmodel/CanvasViewModel.kt
- src/main/kotlin/viewmodel/graph/GraphViewModel.kt
add ability to load databases from sqlite files
> Sqlite load

- src/main/kotlin/view/LoadGraphMenu.kt
feat(db): load from neo4j added
> feat(db): load from neo4j added

- src/main/kotlin/model/layout/ForceAtlas2Layout.kt
- src/main/kotlin/view/AlgorithmSubMenu.kt
- src/main/kotlin/view/algos/BridgeFinderView.kt
- src/main/kotlin/viewmodel/CanvasViewModel.kt
- src/main/kotlin/viewmodel/algos/BridgeFinderViewModel.kt
- src/main/kotlin/viewmodel/graph/GraphViewModel.kt
This implementation paint's nodes into red if they connected with bridge
> feat: implement sad visualization of bridge finder algorithm
